const data = [
  {
    id: 1,
    name: "Whopper Burger King",
    image: "https://foodking-react.vercel.app/assets/img/food/burger-2.png",
    price: 299,
    rating: 4.5,
    category: "Indian",
    isInCart: false,
  },
  {
    id: 2,
    name: "Ruti with beef slice",
    image: "https://foodking-react.vercel.app/assets/img/food/beef-ruti.png",
    price: 349,
    rating: 4.7,
    category: "Indian",
    isInCart: false,
  },
  {
    id: 3,
    name: "Chiness pasta",
    image: "https://foodking-react.vercel.app/assets/img/food/pasta-2.png",
    price: 399,
    rating: 4.6,
    category: "Indian",
    isInCart: false,
  },
  {
    id: 4,
    name: "Pepperoni Pizza",
    image: "https://foodking-react.vercel.app/assets/img/food/pizza-3.png",
    price: 299,
    rating: 4.4,
    category: "Indian",
    isInCart: false,
  },
  {
    id: 5,
    name: "fast food combo",
    image: "https://foodking-react.vercel.app/assets/img/food/main-food-2.png",
    price: 349,
    rating: 4.5,
    category: "Indian",
    isInCart: false,
  },
  {
    id: 6,
    name: "ruti with chiken",
    image: "https://foodking-react.vercel.app/assets/img/food/ruti.png",
    price: 279,
    rating: 4.3,
    category: "Indian",
    isInCart: false,
  },
  {
    id: 7,
    name: "grilled chiken",
    image: "https://foodking-react.vercel.app/assets/img/food/grilled-2.png",
    price: 249,
    rating: 4.2,
    category: "Pizza",
    isInCart: false,
  },
  {
    id: 8,
    name: "Pepperoni Pizza",
    image: "https://foodking-react.vercel.app/assets/img/food/pizza-3.png",
    price: 299,
    rating: 4.6,
    category: "Pizza",
    isInCart: false,
  },
  {
    id: 9,
    name: "Ruti with beef slice",
    image: "https://foodking-react.vercel.app/assets/img/food/beef-ruti.png",
    price: 199,
    rating: 4.1,
    category: "Pizza",
    isInCart: false,
  },
  {
    id: 10,
    name: "Cheeseburger",
    image: "https://foodking-react.vercel.app/assets/img/food/ruti.png",
    price: 159,
    rating: 4.0,
    category: "Burger",
    isInCart: false,
  },
  {
    id: 11,
    name: "Chicken Burger",
    image: "https://foodking-react.vercel.app/assets/img/food/burger-2.png",
    price: 179,
    rating: 4.3,
    category: "Burger",
    isInCart: false,
  },
  {
    id: 12,
    name: "fast food combo",
    image: "https://foodking-react.vercel.app/assets/img/food/main-food-2.png",
    price: 199,
    rating: 4.2,
    category: "Burger",
    isInCart: false,
  },
];
export { data };
